### ISSUE TITLE
Xverse Bitcoin Wallet address error

### ISSUE THREAD

**Issue by Mazowiecki** [hirosystems/connect#327]
Hello, I'm using this package to gather Bitcoin addresses. Hiro Wallet works fine but it's not with Xverse Wallet. 

This is the code that shows the modal where the user can pick a wallet and it returns Its address. Is there maybe an option to not show Xverse wallet on this modal?

export const getWalletAddress = (onSuccess: (key: string) => void): void => {
  const userSession = new UserSession();
  showConnect({
    appDetails,
    onFinish: () => {
      onSuccess(userSession.loadUserData()?.profile?.btcAddress?.p2tr?.mainnet || '');
    },
    userSession
  });
};

Hiro:
![Zrzut ekranu 2023-07-18 o 17 53 46](https://github.com/hirosystems/connect/assets/29356602/2b67182a-2b2d-466d-a749-1825af3606fb)

Xverse:
<img width="167" alt="Zrzut ekranu 2023-07-18 o 17 53 59" src="https://github.com/hirosystems/connect/assets/29356602/6e7ac866-fe6d-43ad-9374-37e877020d91">

**Comment by janniks** [comment]
Hi, 👋🏻
Hiro Wallet was trying this out and it wasn’t really an official API yet.
cc @yknl Maybe Xverse can easily add the same field
Also, we’re collaborating with different wallet and working on new standards for requesting accounts, since the current solutions aren’t very clean. Hope to have more updates soon

**Comment by smcclellan** [comment]
@Mazowiecki I'll close this for now based on @janniks's answer. Thank you for filing!
